### ISSUE TITLE
Not an actual issue, but a question about releases that may help debug another issue

### ISSUE THREAD

**Issue by brian6932** [jsoncomma/jsoncomma#5]
I've written a scoop manifest for this repo, and it ran into a similar issue that I had previously with a different repo, so your insight would be very useful @math2001
https://github.com/ScoopInstaller/Excavator/issues/8#issuecomment-1090126028
Have any releases been modified in the past day?
Like as in, were any removed, and/or reverted?

**Comment by math2001** [comment]
Nah, I haven't touched this repo for more than a year.
